databases:
  - name: foot_and_walk
    databaseName: foot_and_walk
    user: foot_and_walk_user
    region: singapore
    plan: free

services:
  - type: web
    name: foot_and_walk_chat
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn aol.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foot_and_walk
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


    autoDeploy: true
