# Generated by Django 5.1.3 on 2024-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difymodel',
            name='answer',
            field=models.CharField(max_length=600, verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='difymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日時'),
        ),
        migrations.AlterField(
            model_name='difymodel',
            name='query',
            field=models.TextField(max_length=300, verbose_name='質問内容'),
        ),
    ]
