# Generated by Django 5.0.4 on 2024-11-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_difymodel_answer_alter_difymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difymodel',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='回答'),
        ),
    ]
