# Generated by Django 5.0.4 on 2024-11-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_difymodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difymodel',
            name='answer',
            field=models.CharField(max_length=2500, verbose_name='回答'),
        ),
    ]
